config/routes.rb
Fotografi::Application.routes.draw do

	root :to => "photos#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resources :users
  resources :sessions
  resources :photos
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image, :user_id, :description, :title
  mount_uploader :image, ImageUploader

  validates_presence_of :image

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :full_name, :email, :password, :password_confirmation, :twitter

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
    def not_authenticated
      redirect_to login_url, :alert => "First log in to view this page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :destroy]

  def index
    @photos = Photo.order("created_at desc").all
    expires_in 24.hours

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  def show
    @photo = Photo.find(params[:id])
    expires_in 365.days, public: true

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(params[:photo])
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully uploaded.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }

      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
      if user
        redirect_back_or_to root_url, :notice => "Logged in!"
      else
        flash.now.alert = "Email or password was invalid."
      end
  end

  def destroy
	 logout
	 redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_login, :only => [:edit, :show]

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        redirect_to root_path, :notice => 'User was successfully updated.'
        # format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        # format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        # format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if ENV["SITE_TITLE"].nil? %>
<%= link_to "My Photographs", root_path, :class => 'brand' %>
<% else %>
<%= link_to ENV["SITE_TITLE"], root_path, :class => 'brand' %>
<% end %>
<div class="nav-collapse collapse">
<ul class="nav">
	<% if current_user %>
		<li>
			<%= link_to 'Upload Photo', new_photo_path %>
		</li>
		<li>
			<%= link_to 'Edit User', edit_user_path(current_user) %>
		</li>	
		<li>
			<%= link_to "Log out", logout_path %>
		</li>
	<% else %>
		<li>
			<%= link_to "Log in", login_path  %>
		</li>
	<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><% if ENV["SITE_TITLE"].nil? %>My Photos<% end %><%= ENV["SITE_TITLE"] %>
        <%= content_for?(:title) ? yield(:title) : "" %></title>
      <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Photographs" %>">
        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= yield(:head) %>
      </head>
      <body class="<%= controller_name %> <%= action_name %>">
        <div id="fb-root"></div>
        <script>
          (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
        </script>
        <header class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <div class="container">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar">
                </span>
                <span class="icon-bar">
                </span>
                <span class="icon-bar">
                </span>
              </a>
              <%= render 'layouts/navigation' %>
            </div>
          </nav>
        </header>
        <div id="main" role="main">
          <div class="container">
            <div class="content">
              <div class="row">
                <div class="span12">
                  <%= render 'layouts/messages' %>
                  <%= yield %>
                </div>
              </div>
              <footer>
              </footer>
            </div>
          </div>
          <!--! end of .container -->
        </div>
        <!--! end of #main -->
        <script type="text/javascript">
          (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
        </script>
      </body>
    </html>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <div>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <p>Please make sure you are only uploading a
    <strong>JPEG</strong>,
    <strong>JPG</strong>,
    <strong>PNG</strong>, or
    <strong>GIF</strong>. Otherwise your file will not upload.</p>
  <%= hidden_field_tag :photo_user_id, current_user.id %>
  <p><%= f.submit "Upload Photo" %></p>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
  <div class="photo-group">
    <div class="photo photo-wrapper">
      <% if photo.title %>
        <span class="photo-title"><%= link_to photo.title , photo_path(photo) %></span>
      <% end %>
      <%= image_tag photo.image_url, :class => 'img-rounded'%>
      <div class="social-links">
        <div class="g-plusone" data-size="medium" data-href="<%= photo_url(photo) %>"></div>
        <br />
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= photo_url(photo) %>" data-text="<%= photo.title %>" data-via="<%= photo.user.twitter %>" data-hashtags="photo">Tweet</a>
        <script>
          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
        <br />
        <div class="fb-like" data-href="<%= photo_url(photo) %>" data-send="false" data-layout="button_count" data-width="107" data-show-faces="false"></div>
      </div>
      <% if photo.user.full_name %>
        <span class="taken-by">Photo taken by
          <%= photo.user.full_name %></span>
      <% end %>
      <% if current_user %>
        <span class="admin-links">
          <i class="icon-edit"></i>
          <%= link_to 'Edit Photo', edit_photo_path(photo) %>
          |
          <i class="icon-remove"></i>
          <%= link_to 'Delete Photo', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      <% end %>
    </div>
  </div>
  <br />
<% end %>
<br />

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<% content_for :description do %><%= @photo.description %><% end %>
<% content_for :title do %><%= @photo.title %><% end %>

<h1>
  <%= @photo.title %>
</h1>
<p>
  <%= @photo.description %>
</p>
<p>
  <%= image_tag @photo.image_url, :class => 'img-rounded'%>
</p>

<% if current_user %>
  <div class="btn-group">
    <button class="btn"><i class="icon-edit"></i> <%= link_to 'Edit', edit_photo_path(@photo) %> |
    <button class="btn"><i class="icon-remove"></i> <%= link_to 'Back', photos_path %>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing <%= @user.full_name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back Home', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @user.full_name %>
</h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back Home', root_path %>